### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by purcell**
Untested, but this is roughly what I was thinking. You'll need 65967bf anyway.

### CODE REVIEW

**Comment by purcell** [comment]
See https://github.com/milkypostman/melpa/pull/2371

**Comment by purcell** [comment]
Cool, did it work? Wow.

**Comment by xuchunyang** [comment]
Not work yet. (First time to receive a PR)

The  `osx-dictionary--load-dir` is not set. I don't know how to find current package's directory path. Any suggestion?

**Comment by purcell** [comment]
`(file-name-as-directory (file-name-directory load-file-name))` should do it (I made a mistake in the code I sent), but you need to load the file with `M-x load-file`, not `M-x eval-buffer`.

**Comment by purcell** [comment]
So

```el
(defconst osx-dictionary--load-dir (file-name-as-directory (file-name-directory load-file-name)))
```

**Comment by xuchunyang** [comment]
It works now. Thank you!

**Comment by purcell** [comment]
Woo!

**Pull request merged**
